export {
  setVillages,
  setVillageReviews,
  setNewVillageReview,
  setHotelReviews,
  setNewHotelReview,
  setRestaurantReviews,
  setNewRestaurantReview,
  setFamousReviews,
  setNewFamousReview,
  setTourReviews,
  setNewTourReview,
  setCraftReviews,
  setNewCraftReview,
  setCategories,
  setLoading,
  setLan,
  setStaticWord,
} from './store/action';
